#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jackross\Commands\{CalculatorCommand, SumCommand, SckobkiCommand, ServerCommand, ClientCommand};

$application = new \Symfony\Component\Console\Application('Console App');
$application->add(new SumCommand());
$application->add(new SckobkiCommand());
$application->add(new CalculatorCommand());
$application->add(new ServerCommand());
$application->add(new ClientCommand());
$application->run();